DATALOADER:
  TRAIN:
    BATCH_SIZE: 32
    SAMPLER: "SequentialSampler"
#    SAMPLER: "RandomSampler"
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 8

DATASET:
  ROOT: "/root/lanyun-tmp/ldj/AnomalyVPT_test_only/dataset"
  NUM_SHOTS: 256
  MIX: False

OPTIM:
  NAME: "adamw"
  LR: 0.002
  MAX_EPOCH: 80
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-6
  WEIGHT_DECAY: 0.02

TRAIN:
  CHECKPOINT_FREQ: 3
  PRINT_FREQ: 5


INPUT:
  SIZE: (224, 224)
  PIXEL_MEAN: (0.48145466, 0.4578275, 0.40821073)
  PIXEL_STD: (0.26862954, 0.26130258, 0.27577711)

MODEL:
  VP_LENGTH: 16 # 16
  INIT_WEIGHTS: ""
  PATCH_SIZE: 16
  MODEL_NAME: "ViT-B-16"
