DATALOADER:
  TRAIN:
    BATCH_SIZE: 32
    SAMPLER: "SequentialSampler"
    # SAMPLER: "RandomSampler"
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 4

DATASET:
  ROOT: "data/users/ldj/dataset"
  NUM_SHOTS: 256
  MIX: True

OPTIM:
  NAME: "adamw"
  LR: 0.002
  MAX_EPOCH: 80
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-6
  WEIGHT_DECAY: 0.01

TRAIN:
  CHECKPOINT_FREQ: 2
  PRINT_FREQ: 5


INPUT:
  SIZE: (336, 336)
  PIXEL_MEAN: (0.48145466, 0.4578275, 0.40821073)
  PIXEL_STD: (0.26862954, 0.26130258, 0.27577711)

MODEL:
  VP_LENGTH: 16 # 16
  INIT_WEIGHTS: ""
  PATCH_SIZE: 14
  MODEL_NAME: "ViT-L-14-336"
